#ifndef TLS_13_ALERT_CONSTANTS
#define TLS_13_ALERT_CONSTANTS

    #define WARNING_ALERT 1
    #define FATAL_ALERT 2

    #define CLOSE_NOTIFY_ALERT 0
    #define UNEXPECTED_MESSAGE_ALERT 10
    #define BAD_RECORD_MAC_ALERT 20
    #define RECORD_OVERFLOW_ALERT 22
    #define HANDSHAKE_FAILURE_ALERT 40
    #define BAD_CERTIFICATE_ALERT 42
    #define UNSUPPORTED_CERTIFICATE_ALERT 43
    #define CERTIFICATE_REVOKED_ALERT 44
    #define CERTIFICATE_EXPIRED_ALERT 45
    #define CERTIFICATE_UNKNOWN_ALERT 46
    #define ILLEGAL_PARAMETER_ALERT 47
    #define UNKNOWN_CA_ALERT 48
    #define ACCESS_DENIED_ALERT 49
    #define DECODE_ERROR_ALERT 50
    #define DECRYPT_ERROR_ALERT 51
    #define PROTOCOL_VERSION_ALERT 70
    #define INSUFFICIENT_SECURITY_ALERT 71
    #define INTERNAL_ERROR_ALERT 80
    #define INAPPROPRIATE_FALLBACK_ALERT 86
    #define USER_CANCELED_ALERT 90
    #define MISSING_EXTENSION_ALERT 109
    #define UNSUPPORTED_EXTENSION_ALERT 110
    #define UNRECOGNIZED_NAME_ALERT 112
    #define BAD_CERTIFICATE_STATUS_RESPONSE_ALERT 113
    #define UNKNOWN_PSK_IDENTITY_ALERT 115
    #define CERTIFICATE_REQUIRED_ALERT 116
    #define NO_APPLICATION_PROTOCOL_ALERT 120

    char* get_alert_name(int type);

#endif